DROP TABLE IF EXISTS TBL_AIRPORT;
DROP TABLE IF EXISTS TBL_FLIGHT;

CREATE TABLE TBL_AIRPORT(
  id int PRIMARY KEY,
  gmt VARCHAR (250) DEFAULT NULL,
  iata_code VARCHAR (250) DEFAULT NULL,
  city_iata_code VARCHAR (250) DEFAULT NULL,
  icao_code VARCHAR (250) DEFAULT NULL,
  country_iso2 VARCHAR (250) DEFAULT NULL,
  geoname_id VARCHAR (250) DEFAULT NULL,
  latitude VARCHAR (250) DEFAULT NULL,
  longitude VARCHAR (250) DEFAULT NULL,
  airport_name VARCHAR (250) DEFAULT NULL,
  country_name VARCHAR (250) DEFAULT NULL,
  phone_number VARCHAR (250) DEFAULT NULL,
  timezone VARCHAR (250) DEFAULT NULL
);

CREATE TABLE TBL_FLIGHT(
  id int PRIMARY KEY,
  flight CLOB DEFAULT NULL
);
